### ISSUE TITLE
为什么启动不了呢

### ISSUE THREAD

**Issue by fndppx** [JasonStu/ReactNative_Shopping#11]
![b8d21b23-1ce3-4f83-93c1-da30531ff541](https://cloud.githubusercontent.com/assets/7971897/21879834/34e6e85a-d8d6-11e6-9380-3e5b775a8df3.png)

**Comment by HAPENLY** [comment]
这个问题你解决了吗？

**Comment by 775821shiwoa** [comment]
解决了， 把项目当中node模块全部删除， 之后进入项目根目录 npm install 就好了。
