### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by wintersweet123** [JasonStu/ReactNative_Shopping#2]
显示缺文件啊，RCTBundleURLProvider.h  not found

**Comment by JasonStu** [comment]
node的服务器还没加载好文件,cmd+R 尝试几次

**Comment by wintersweet123** [comment]
![2016-09-27 3 05 47](https://cloud.githubusercontent.com/assets/10936828/18863444/ebe80e9c-84c3-11e6-8544-61f59d81cd8a.png)

**Comment by JasonStu** [comment]
这个不是我项目造成的问题,你可以去RN官方github找 ,你先尝试一下 rnpm link 如果不行自行百度

**Comment by wintersweet123** [comment]
好吧
